### ISSUE TITLE
update to fontconfig 2.11.1

### ISSUE THREAD

**Issue by BingTSC** [nice-software/gtk-win32#10]
anyone can provide the patch?

**Comment by pbor** [comment]
why was this closed? I think it is a valid report, but we did not have time to fix it yet... if you fixed it yourself, a pull request would be very appreciated

**Comment by BingTSC** [comment]
I fixed it, and made a fork or your branch, will check commits and post link later.

**Comment by BingTSC** [comment]
Here it's the repo to get fontconfig 2.11.1 work with Pango: (I only build Pango, not GTK3)

https://github.com/TechSmith/gtk-win32

**Comment by nacho** [comment]
can you provide pull requests?

**Comment by BingTSC** [comment]
can you access this repo I forked from you:  https://github.com/TechSmith/gtk-win32
we also starts to provide 2015 branch there.

**Comment by nacho** [comment]
Hey, pushed your patches rebased. Thanks a lot.

**Comment by nacho** [comment]
For 2015 you might want to have a look also at: https://github.com/hexchat/gtk-win32/tree/2015
