### ISSUE TITLE
Update to glib 2.44

### ISSUE THREAD

**Issue by nacho** [nice-software/gtk-win32#5]
so I started the update to glib 2.44 in the wip/hrebase and I get the next errors:
glib :        "C:\gtk-build\build\Win32\glib\build\win32\vs12\glib.sln" (default target) (1) ->
glib :        "C:\gtk-build\build\Win32\glib\build\win32\vs12\gio.vcxproj" (default target) (9) ->
glib :        (ClCompile target) ->
glib :          c1 : fatal error C1083: Cannot open source file: '..\..\..\gio\gcontextspecificgroup.c': No such file or
 directory [C:\gtk-build\build\Win32\glib\build\win32\vs12\gio.vcxproj]
glib :          c1 : fatal error C1083: Cannot open source file: '..\..\..\gio\ghttpproxy.c': No such file or directory
[C:\gtk-build\build\Win32\glib\build\win32\vs12\gio.vcxproj]
glib :          c1 : fatal error C1083: Cannot open source file: '..\..\..\gio\glistmodel.c': No such file or directory
[C:\gtk-build\build\Win32\glib\build\win32\vs12\gio.vcxproj]
glib :          c1 : fatal error C1083: Cannot open source file: '..\..\..\gio\gliststore.c': No such file or directory
[C:\gtk-build\build\Win32\glib\build\win32\vs12\gio.vcxproj]
glib :          c1 : fatal error C1083: Cannot open source file: '..\..\..\gio\gsimpleiostream.c': No such file or direc
tory [C:\gtk-build\build\Win32\glib\build\win32\vs12\gio.vcxproj]

**Comment by pbor** [comment]
I guess you need to regenerate the projects or take the ones from the new
tarballs so they contain the new files
Il 01/Apr/2015 12:36 "Ignacio Casal Quinteiro" <notifications@github.com>
ha scritto:

**Comment by nacho** [comment]
actually the problem is that I regenerated the files but I forgot to update the link of the tarball :)

**Comment by nacho** [comment]
After updating the link now it seems to build fine
