### ISSUE TITLE
support unicode?

### ISSUE THREAD

**Issue by BingTSC** [nice-software/gtk-win32#9]
Really thank you for clear build instructions so I'm able to build it successfully.

however I got the problem when using it.  I guess it's due to my project is set to build "use unicode character set", so it's mixing char/wchar ...

Here is the crash stack, 

win32 configuration:
![2015-09-17_1207](https://cloud.githubusercontent.com/assets/5375159/9938818/270bea96-5d35-11e5-8baa-3ac816ffaa85.png)

x64 configuration:
![2015-09-17_1209](https://cloud.githubusercontent.com/assets/5375159/9938819/270e365c-5d35-11e5-9952-5fd1ba345251.png)

do you have a solution? thank you.

**Comment by nacho** [comment]
Hey, we had this problem in the past and we fixed it by removing the boms. See that you need to ensure to have your system language in English when building the binaries. Then I think it should work fine.

**Comment by BingTSC** [comment]
the crash on x64 is due to type definition, the DIR->handle is a long, which is only 32bit, but when build x64, the pointer is 64 bit, so it has been truncated. after change long to int_ptr fixed the crash. the first one seems go away when update to fontconfig 2.11.1.

**Comment by nacho** [comment]
Can you also provide some patch for this?

**Comment by BingTSC** [comment]
sure. when I set everything clean :-)

**Comment by BingTSC** [comment]
the patch is already in this commit: https://github.com/nice-software/gtk-win32/commit/1cedf1bd55e732b141132e8b06019dada79523dd

close this one too.
